version: '3.4'

services:
  db:
    image: "mcr.microsoft.com/mssql/server:2017-latest"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=AngryTurkeyBirds2021$$

  supermarket.api:
    image: ${DOCKER_REGISTRY-}supermarketapi
    build:
      context: .
      dockerfile: Supermarket.API/Dockerfile
    depends_on:
      - db
